// Top-level build file
plugins {
    alias libs.plugins.android.app apply false
    alias libs.plugins.android.lib apply false
    alias libs.plugins.kotlin.android apply false
    alias libs.plugins.kotlin.kapt apply false
    alias libs.plugins.ksp apply false
    alias libs.plugins.ktx.serialization apply false
}

allprojects {
    repositories {
        mavenCentral()
        google()
    }
    configurations.configureEach {
        resolutionStrategy.dependencySubstitution {
            substitute module("org.secuso.pfacore:model") using project(":model")
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}